"""removendo tabelas de pedidos

Revision ID: 32b5b9115614
Revises: d1ddca58fbf6
Create Date: 2026-03-24 17:44:35.158189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b5b9115614'
down_revision: Union[str, Sequence[str], None] = 'd1ddca58fbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('pedidos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('usuario', sa.INTEGER(), nullable=True),
    sa.Column('preco', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=True),
    sa.Column('sabor', sa.VARCHAR(), nullable=True),
    sa.Column('tamanho', sa.VARCHAR(), nullable=True),
    sa.Column('preco_unitario', sa.FLOAT(), nullable=True),
    sa.Column('pedido', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pedido'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
