"""descricao

Revision ID: 3d6e9b0e8963
Revises: bebdc56d49df
Create Date: 2026-06-11 21:57:38.828018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6e9b0e8963'
down_revision: Union[str, Sequence[str], None] = 'bebdc56d49df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercicios')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('series', sa.INTEGER(), nullable=True),
    sa.Column('repeticoes', sa.INTEGER(), nullable=True),
    sa.Column('carga', sa.FLOAT(), nullable=True),
    sa.Column('treino_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['treino_id'], ['treinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
