"""tornar_carga_opcional

Revision ID: 69cc9ef46c5b
Revises: 32b5b9115614
Create Date: 2026-03-31 15:10:02.278712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cc9ef46c5b'
down_revision: Union[str, Sequence[str], None] = '32b5b9115614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
