"""adicionar vinculo aluno personal

Revision ID: a28f82496f4d
Revises: b196a4091cf9
Create Date: 2026-09-06 21:43:37.554730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28f82496f4d'
down_revision: Union[str, Sequence[str], None] = 'b196a4091cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_usuarios_personal_id', 'usuarios', ['personal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuarios_personal_id', type_='foreignkey')
        batch_op.drop_column('personal_id')

    # ### end Alembic commands ###
