"""criar tabelas de academias e vinculos de personais

Revision ID: b196a4091cf9
Revises: 3d6e9b0e8963
Create Date: 2026-09-06 21:17:10.916398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b196a4091cf9'
down_revision: Union[str, Sequence[str], None] = '3d6e9b0e8963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidade', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('especialidade')

    # ### end Alembic commands ###
