"""teste_autogenerate

Revision ID: bebdc56d49df
Revises: 69cc9ef46c5b
Create Date: 2026-06-08 22:43:52.555653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bebdc56d49df'
down_revision: Union[str, Sequence[str], None] = '69cc9ef46c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercicios_catalogo', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_exercicios_catalogo_api_id'), ['api_id'])

    with op.batch_alter_table('treinos', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_email'), ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuarios_email'), type_='unique')
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('treinos', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('exercicios_catalogo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_exercicios_catalogo_api_id'), type_='unique')

    # ### end Alembic commands ###
